repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.2"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
        exclude: ^tests/
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.10"
    hooks:
      - id: vulture
        exclude: ^tests/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.9.0"
    hooks:
      - id: mypy
        args: ["--strict", "--ignore-missing-imports"]
        exclude: ^tests/
        additional_dependencies:
          - "mypy-extensions>=1.0.0"
          - "typing-extensions>=4.1.0"
          - "types-pyautogui"
          - "types-pywin32"
          - "types-psutil"
          - "pytest>=7.0.0"
          - "numpy>=1.20.0"
          - "opencv-python"
          - "rx"

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.33.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
